title: ""
description: "Bioinformatician | Genomics | RNA Biology"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

header_pages:
  - projects.md
  - publications.md
  - outreach.md
  - press.md
 
