title: ""
description: "Bioinformatician | Genomics | RNA Biology"

theme: minima
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache

header_pages:
  - projects.md
  - publications.md
  - outreach.md
  - press.md
 
